const products = [
  {
    id:1,
    name:'polo',
    price:30,
    imagen:'./imagen/images1.jpg'
  },
  {
    id:2,
    name:'polo',
    price:30,
    imagen:'./imagen/images2.jpg'
  },
  {
    id:3,
    name:'polo',
    price:30,
    imagen:'./imagen/images3.png'
  },
  {    
    id:4,
    name:'polo',
    price:30,
    imagen:'./imagen/images4.png'
  },
  {
    id:5,
    name:'polo',
    price:30,
    imagen:'./imagen/images5.png'
  },
  {
    id:6,
    name:'polo',
    price:30,
    imagen:'./imagen/images6.png'
  },
  {
    id:7,
    name:'polo',
    price:30,
    imagen:'./imagen/images7.png'
  },
  {
    id:8,
    name:'polo',
    price:30,
    imagen:'./imagen/images8.png'
  },
  {
    id:9,
    name:'polo',
    price:30,
    imagen:'./imagen/images9.png'
  },
  {
    id:10,
    name:'polo',
    price:30,
    imagen:'./imagen/imagen10.png'
  },
  {
    id:11,
    name:'polo',
    price:30,
    imagen:'./imagen/images11.png'
  },
  {
    id:12,
    name:'polo',
    price:30,
    imagen:'./imagen/images12.jpg'
  },
  {
    id:13,
    name:'polo',
    price:30,
    imagen:'./imagen/images13.jpg'
  },
  {
    id:14,
    name:'polo',
    price:30,
    imagen:'./imagen/images14.jpg'
  },
  {
    id:15,
    name:'polo',
    price:30,
    imagen:'./imagen/images15.jpg'
  },
  {
    id:16,
    name:'polo',
    price:30,
    imagen:'./imagen/images16.png'
  },
  {
    id:17,
    name:'polo',
    price:30,
    imagen:'./imagen/images17.png'
  },
  {
    id:18,
    name:'polo',
    price:30,
    imagen:'./imagen/images18.png'
  },
  {
    id:19,
    name:'polo',
    price:30,
    imagen:'./imagen/images19.png'
  },
  {
    id:20,
    name:'polo',
    price:30,
    imagen:'./imagen/images20.png'
  }
]